# Generated by Django 2.1.5 on 2019-11-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
