# Generated by Django 2.1.5 on 2019-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddash', '0002_auto_20191107_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_url', models.CharField(max_length=200)),
                ('recipe_titel', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
